replicaCount: 1

services:
  - name: "leumi-ltv-service"
    image:
      repository: "637423493523.dkr.ecr.eu-west-1.amazonaws.com/leumi-ltv-service"
      tag: "latest"  # Will be dynamically updated by Argo CD Image Updater
      pullPolicy: Always
    service:
      name: "leumi-ltv-service"
      type: ClusterIP
      port: 8080
      role: "dev"
      contextPath: "/leumi-ltv-service"
  - name: "leumi-pti-service"
    image:
      repository: "637423493523.dkr.ecr.eu-west-1.amazonaws.com/leumi-pti-service"
      tag: "latest"  # Will be dynamically updated by Argo CD Image Updater
      pullPolicy: Always
    service:
      name: "leumi-pti-service"
      type: ClusterIP
      port: 8080
      role: "dev"
      contextPath: "/leumi-pti-service"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

livenessProbe:
  httpGet:
    path: /actuator/health
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /actuator/health
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}

configVars: {}
