apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.service.name }}-config
  labels:
    app.kubernetes.io/managed-by: Helm
data:
  SERVER_SERVLET_CONTEXT_PATH: {{ .Values.service.contextPath | quote }}
  {{- range $key, $value := .Values.configVars }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  MANAGEMENT_ENDPOINT_HEALTH_INDICATORS_REDIS_VITALITYREPORT: "false"
  MONGO_DB_NAME: "ltv-lab"
  PORT: '8080'
  MONGO_CONNECTION_STRING: "mongodb+srv://mortgages:mortgages123@mortgages-pl-0.38k3e.mongodb.net/ltv-ghost?authSource=admin"