{{- range .Values.services }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}-deployment
  labels:
    app: {{ .name }}
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .name }}
      role: {{ .service.role }}
  template:
    metadata:
      labels:
        app: {{ .name }}
        role: {{ .service.role }}
    spec:
      containers:
        - name: {{ .name }}
          image: "{{ .image.repository }}:{{ .image.tag }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          ports:
            - containerPort: {{ .service.port }}
          livenessProbe:
            httpGet:
              path: {{ .service.contextPath }}/actuator/health
              port: {{ .service.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: {{ .service.contextPath }}/actuator/health
              port: {{ .service.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
{{- end }}
